- name: Netflix Tech Blog
  url: https://netflixtechblog.com/feed
  type: rss
  topics: [infra, ML]

- name: OpenAI Blog
  url: https://openai.com/blog/rss
  type: rss
  topics: [LLM, AI]

- name: Cloudflare Blog
  url: https://blog.cloudflare.com/rss/
  type: rss
  topics: [network, infra]

- name: Tailscale Blog
  url: https://tailscale.com/blog/index.xml
  type: rss
  topics: [devex, networking]

- name: Hugging Face
  url: https://huggingface.co/blog/feed
  type: rss
  topics: [ML, open source]

- name: Google AI Blog
  url: https://ai.googleblog.com/atom.xml
  type: rss
  topics: [AI, research]

- name: Microsoft AI Blog
  url: https://blogs.microsoft.com/ai/feed/
  type: rss
  topics: [AI, cloud]

- name: NVIDIA AI Blog
  url: https://blogs.nvidia.com/blog/category/ai/feed/
  type: rss
  topics: [AI, hardware]

- name: Anthropic News
  url: https://fetchrss.com/feed/aJOq74FhyokTaJOq1sq-Jbci.rss
  type: rss
  topics: [AI, safety]

- name: Mistral AI Blog
  url: https://mistral.ai/blog/rss.xml
  type: rss
  topics: [AI, LLM]

- name: Databricks Blog
  url: https://www.databricks.com/blog/category/artificial-intelligence/feed
  type: rss
  topics: [AI, data]

- name: The Verge AI
  url: https://www.theverge.com/artificial-intelligence/rss/index.xml
  type: rss
  topics: [AI, news]

- name: TechCrunch AI
  url: https://techcrunch.com/tag/artificial-intelligence/feed/
  type: rss
  topics: [AI, news]

- name: NYTimes AI
  url: https://rss.nytimes.com/services/xml/rss/nyt/ArtificialIntelligence.xml
  type: rss
  topics: [AI, news]

- name: Washington Post AI
  url: https://feeds.washingtonpost.com/rss/business/artificial-intelligence
  type: rss
  topics: [AI, news]
