name: Daily Blog Summary

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run crawler
        run: python scripts/fetch_articles.py
      - name: Commit & push summaries
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch
          git checkout ${{ github.ref_name }}
          git add data/summaries.json || echo "No changes to add"
          git diff --cached --quiet || git commit -m "Daily summary update"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
